Repository AY2223S1-CS2113-T18-1b/tp, pull requests merged in 2022-10, with the labels that each got.

#40 fixing delete command
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/RemoveCommand.java
Labels: type.Bug, priority.High

#44 adding storage assertions
  src/main/java/seedu/duke/Storage.java
Labels: type.Task, priority.High

#46 adding remove tests
  src/main/java/seedu/duke/RemoveCommand.java
  src/test/java/seedu/duke/RemoveCommandTest.java
Labels: type.Task, priority.High

#59 Adding List Tests
  src/test/java/seedu/duke/ListCommandTest.java
Labels: type.Task, priority.High

#65 Adding list sequence diagram
  docs/UML Diagrams/listSequence.puml
Labels: type.Task, priority.High

#66 Added tests for AddCommand, Media, Movie, TV Show and RemoveCommand.
  docs/UML Diagrams/addCommandSequence.puml
  src/main/java/seedu/duke/Movie.java
  src/main/java/seedu/duke/TvShow.java
  src/test/java/seedu/duke/AddCommandTest.java
  src/test/java/seedu/duke/ListCommandTest.java
  src/test/java/seedu/duke/MediaTest.java
  src/test/java/seedu/duke/MovieTest.java
  src/test/java/seedu/duke/RemoveCommandTest.java
  src/test/java/seedu/duke/TvShowTest.java
Labels: type.Task, priority.High

#68 adding clear tests
  src/test/java/seedu/duke/ClearCommandTest.java
  src/test/java/seedu/duke/ListCommandTest.java
  src/test/java/seedu/duke/RemoveCommandTest.java
Labels: type.Task, priority.High

#70 Added addCommand and findCommand sequence diagrams.
  docs/UML Diagrams/addCommandSequence.puml
  docs/UML Diagrams/findCommandSequence.puml
  src/main/java/seedu/duke/Parser.java
Labels: type.Task, priority.High

#71 Added diagrams to developer guide
  docs/DeveloperGuide.md
  docs/imgs/AddCommandSequence.png
  docs/imgs/FindCommandSequence.png
  docs/imgs/ListCommandSequence.png
Labels: priority.High

#72 updated Developer Guide
  data/stored.txt
  docs/DeveloperGuide.md
  docs/UML Diagrams/listSequence.puml
  docs/imgs/ListCommandSequence.png
Labels: type.Task, priority.High

#73 Updated Developer's Guide
  docs/DeveloperGuide.md
  docs/UML Diagrams/findCommandSequence.puml
  docs/imgs/FindCommandSequence.png
Labels: type.Task, priority.High

#74 adding List/Sort Descriptions
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#111 Fixes #81
  data/stored.txt
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/TvShowTest.java
Labels: type.Bug, priority.High

#112 Branch fix add command
  src/main/java/seedu/duke/Parser.java
Labels: type.Bug, priority.High

#113 adding comments
  docs/UserGuide.md
  src/main/java/seedu/duke/AddCommand.java
  src/main/java/seedu/duke/FindCommand.java
  src/main/java/seedu/duke/ListCommand.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/RemoveCommand.java
Labels: type.Task, priority.Medium

#114 adding Features descriptions
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Low

#69 adding UI tests
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Ui.java
  src/test/java/seedu/duke/ClearCommandTest.java
  src/test/java/seedu/duke/UiTest.java
Labels: type.Task, priority.High

#118 adding
  src/main/java/seedu/duke/AddCommand.java
  src/main/java/seedu/duke/ClearCommand.java
  src/main/java/seedu/duke/DukeException.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/RemoveCommand.java
  src/main/java/seedu/duke/ReviewList.java
  src/main/java/seedu/duke/Ui.java
Labels: type.Bug, priority.High

#120 updated user guide, README and AboutUs
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
  docs/team/indraneelparanjape.md
  docs/team/matthewphua.md
  docs/team/nazrulsyahmi.md
  docs/team/ongshaoyong.md
  src/main/java/seedu/duke/FavouriteCommand.java
Labels: type.Task, priority.High
