Repository AY2223S1-CS2113-T18-1b/tp, pull requests merged in 2022-11, with the labels that each got.

#122 Fixed UML diagrams, coding standards errors and documentation.
  docs/UML Diagrams/CommandsClass.puml
  docs/UML Diagrams/MovieClass.puml
  docs/UML Diagrams/addCommandSequence.puml
  docs/UML Diagrams/clearSequence.puml
  docs/UML Diagrams/deleteSequence.puml
  docs/UML Diagrams/favouriteSequence.puml
  docs/UML Diagrams/findCommandSequence.puml
  docs/UML Diagrams/listSequence.puml
  docs/UML Diagrams/sortSequence.puml
  docs/UML Diagrams/style.puml
  docs/imgs/AddCommandSequence.png
  docs/imgs/CommandsClass.png
  docs/imgs/FindCommandSequence.png
  docs/imgs/ListCommandSequence.png
  docs/imgs/MovieClass.png
  docs/imgs/StorageClass.png
  docs/imgs/UiClass.png
  docs/imgs/clearSequence.png
  docs/imgs/deleteSequence.png
  docs/imgs/favouriteSequence.png
  docs/imgs/sortSequence.png
  docs/team/johndoe.md
  src/main/java/seedu/duke/Parser.java
Labels: type.Bug, priority.High

#121 updated sorting method, made spacing consistent and updated user guide
  data/stored.txt
  docs/UserGuide.md
  logger.log.lck
  src/main/java/seedu/duke/Media.java
  src/main/java/seedu/duke/Movie.java
  src/main/java/seedu/duke/SortCommand.java
  src/main/java/seedu/duke/TvShow.java
  src/test/java/seedu/duke/ListCommandTest.java
  src/test/java/seedu/duke/MediaTest.java
  src/test/java/seedu/duke/MovieTest.java
  src/test/java/seedu/duke/RemoveCommandTest.java
  src/test/java/seedu/duke/SortCommandTest.java
  src/test/java/seedu/duke/TvShowTest.java
Labels: type.Task, type.Bug, priority.High

#126 updated add command to make all dates from the future invalid
  logger.log.lck
  src/main/java/seedu/duke/FutureDateException.java
  src/main/java/seedu/duke/InvalidDateException.java
  src/main/java/seedu/duke/Media.java
  src/main/java/seedu/duke/Parser.java
Labels: type.Bug, priority.High, priority.Medium

#128 updated user guide
  docs/UserGuide.md
Labels: type.Task, severity.VeryLow

#130 adding
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Low

#131 Created exceptions and commands packages to organise classes. Added new exceptions. Fixed empty command fields issue.
  docs/team/ongshaoyong.md
  logger.log.lck
  src/main/java/commands/AddCommand.java
  src/main/java/commands/ClearCommand.java
  src/main/java/commands/Commands.java
  src/main/java/commands/FavouriteCommand.java
  src/main/java/commands/FindCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/SortCommand.java
  src/main/java/exceptions/DukeException.java
  src/main/java/exceptions/IllegalCharacterException.java
  src/main/java/exceptions/InvalidCommandException.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/ReviewList.java
  src/test/java/seedu/duke/AddCommandTest.java
  src/test/java/seedu/duke/ClearCommandTest.java
  src/test/java/seedu/duke/FavouriteCommandTest.java
  src/test/java/seedu/duke/ListCommandTest.java
  src/test/java/seedu/duke/MovieTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/RemoveCommandTest.java
  src/test/java/seedu/duke/SortCommandTest.java
  src/test/java/seedu/duke/TvShowTest.java
Labels: type.Enhancement, type.Bug, priority.High

#132 Improved test coverage and updated PPP.
  docs/UML Diagrams/MediaClass.puml
  docs/team/ongshaoyong.md
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/MediaTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Enhancement, priority.High

#133 moved remaining exception files into exceptions folder
  src/main/java/exceptions/FutureDateException.java
  src/main/java/exceptions/InvalidDateException.java
  src/main/java/seedu/duke/Media.java
  src/main/java/seedu/duke/Parser.java
Labels: type.Task, priority.Medium

#134 updated favourite command to follow media type index and updated tests
  data/stored.txt
  logger.log.lck
  src/main/java/commands/FavouriteCommand.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/FavouriteCommandTest.java
Labels: type.Enhancement, priority.High, severity.Medium

#136 added to sequence diagrams
  docs/DeveloperGuide.md
  docs/UML Diagrams/clearSequence.puml
  docs/UML Diagrams/deleteSequence.puml
  docs/UML Diagrams/favouriteSequence.puml
  docs/UML Diagrams/sortSequence.puml
  docs/imgs/clearSequence.png
  docs/imgs/clearSequence1.png
  docs/imgs/deleteSequence.png
  docs/imgs/favouriteSequence.png
  docs/imgs/sortSequence.png
Labels: type.Enhancement, type.Task, priority.Medium

#137 Renamed PPP files
  docs/team/indraneelrp.md
  docs/team/naz019.md
  docs/team/redders7.md
Labels: severity.Low

#138 adding
  docs/UserGuide.md
  docs/team/matthewphua.md
  src/main/java/seedu/duke/Parser.java
Labels: priority.Medium

#139 updated naz019 PPP
  docs/team/naz019.md
Labels: type.Task, priority.High

#141 fixed AboutUs links
  docs/AboutUs.md
Labels: type.Task

#150 Fixed storage tampering issue. Updated UserGuide.
  data/stored.txt
  docs/UserGuide.md
  logger.log.lck
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/test/java/seedu/duke/MediaTest.java
  src/test/java/seedu/duke/UiTest.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High, severity.Medium

#151 updated PPP and docs to reflect renaming to myReviews
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#152 updated sequence diagrams for all commands other than add, to include overall Parser activation bar
  docs/DeveloperGuide.md
  docs/UML Diagrams/clearSequence.puml
  docs/UML Diagrams/deleteSequence.puml
  docs/UML Diagrams/favouriteSequence.puml
  docs/UML Diagrams/listSequence.puml
  docs/UML Diagrams/sortSequence.puml
  docs/imgs/ListCommandSequence.png
  docs/imgs/clearSequence.png
  docs/imgs/clearSequence1.png
  docs/imgs/deleteSequence.png
  docs/imgs/favouriteSequence.png
  docs/imgs/sortSequence.png
Labels: type.Task, priority.Medium

#153 Added code quality changes
  data/stored.txt
  docs/team/naz019.md
  logger.log.lck
  src/main/java/commands/AddCommand.java
  src/main/java/commands/Commands.java
  src/main/java/commands/FavouriteCommand.java
  src/main/java/commands/SortCommand.java
  src/main/java/seedu/duke/Media.java
  src/main/java/seedu/duke/Movie.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/ReviewList.java
  src/main/java/seedu/duke/TvShow.java
  src/main/java/seedu/duke/Ui.java
  src/test/java/seedu/duke/MediaTest.java
  src/test/java/seedu/duke/MovieTest.java
  src/test/java/seedu/duke/TvShowTest.java
Labels: type.Task, priority.High

#154 added JavaDocs
  data/stored.txt
  src/main/java/commands/FavouriteCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/SortCommand.java
  src/main/java/seedu/duke/Media.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
Labels: type.Task, priority.Medium

#155 Updated docs
  data/stored.txt
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/imgs/naz019_github_photo.png
  docs/team/naz019.md
  src/main/java/seedu/duke/Ui.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#156 Updated personal PPP. Added JUnit tests for Parser.
  docs/team/redders7.md
  logger.log.lck
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/MediaTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Enhancement, type.Task, priority.High

#160 Added PPP, Refactored find command to include more than one word in search term.
  docs/team/matthewphua.md
  src/main/java/commands/FindCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/FavouriteCommandTest.java
  src/test/java/seedu/duke/ListCommandTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High

#162 Fixed issue with commands with leading whitespaces
  data/stored.txt
  docs/AboutUs.md
  docs/imgs/shaoyong.png
  docs/team/redders7.md
  logger.log.lck
  src/main/java/seedu/duke/Parser.java
Labels: type.Bug, priority.High, severity.High

#166 Added JavaDoc
  src/main/java/seedu/duke/Media.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
Labels: type.Enhancement, severity.VeryLow

#169 Fixed minor UG bugs.
  data/stored.txt
  docs/UserGuide.md
  docs/team/redders7.md
  logger.log.lck
Labels: type.Bug, priority.Medium, severity.Low

#176 updated PPP
  docs/team/naz019.md
Labels: type.Task, priority.High

#177 shortened PPP
  docs/team/naz019.md
Labels: type.Task, priority.High

#178 updated PPP links
  docs/team/naz019.md
Labels: type.Task, priority.High

#179 Added more javadoc
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
Labels: priority.Medium

#181 updated favourites command
  src/main/java/commands/FavouriteCommand.java
Labels: type.Task, type.Bug, priority.High

#183 updated sort
  src/main/java/commands/SortCommand.java
Labels: type.Task, priority.High
